name: ugnest_repositories
description: UserRepository example for ugnest.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.7
  jsonrpc2: ^2.0.3+1
  loggable: ^1.0.1
  shared_preferences: ^0.5.3+5
  pedantic: ^1.8.0+1
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.7.1
  json_serializable: ^3.2.3
